### ISSUE TITLE
Cannot update to zoneminder.i686 0:1.30.0-5.fc25

### ISSUE THREAD

**Issue by mhirsch** [knnniggett/zmrepo#1]
I have an i386 Fedora 25 computer running zoneminder from zmrepo. When I run a `dnf upgrade` today I get an error indicating that zoneminder is being skipped.

```
Skipping packages with broken dependencies:
 zoneminder                  i686              1.30.0-5.fc25                  zmrepo               7.3 M
```
Using `yum-depricated` I found that `zoneminder-1.30.0-5.fc25.i686` is failing on a missing dependency for `perl(IO::Socket::Multicast)`. I have  rpmfusion disabled on the system and all packages from rpmfusion uninstalled. The only packages installed are from fedora and zmrepo.

**Comment by knight-of-ni** [comment]
Hi,
Thank you for reporting this, but we don't handle packaging issues here. Please report these to the user forum. Thank you.

**Comment by mhirsch** [comment]
Sorry about that. Do you mean the zonmeinder general forums or is there some specific zmrepo forum somewhere?

**Comment by knight-of-ni** [comment]
The general zoneminder user forum, please. We all participate there as well as here. This is just an organizational thing for us. We want to keep issues that do not affect the zoneminder source code out of our github forum. 

I've taken a look at the problem you reported, and I am in the middle of migrating all of zoneminder's missing package dependencies out of zmrepo and into the official Fedora/EPEL repos. The package affecting you, perl-IO-Socket-Multicast, is currently in Fedora testing and should get pushed to Fedora stable repos in a day or so: https://bodhi.fedoraproject.org/updates/FEDORA-2017-b9913738d7

If you still have an issue after a day or so, feel free to create a new thread in the user forum.

**Comment by mhirsch** [comment]
Thanks!
